Add portfolio projects
allenkays/Portfolio-setup-and-mobile-first pull request #2
Opened 2023-07-06 15:32 UTC by allenkays

In this milestone I:

- Added my recent works to the portfolio.
- Added button interactions.
- Added about me section and my stack.
- Updated the styles.css  file to style the portions added to the index page.
- Installed the node modules for linters checks.

2023-07-06 18:02 UTC, Shisui6 requested changes
Hi @allenkays, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 18:02 UTC, Shisui6 commented on index.html
> +            <section class="portfolio">
According to the project requirements, you are to use CSS grid to style the main container of the works section. Currently your main container is not using the CSS grid property. Please update your works section to contain this requirement🙏

2023-07-06 18:02 UTC, Shisui6 commented on index.html
> +                    <h1 class="main-title">About me</h1>
Kindly update this element to use another `<hx>` tag apart from `<h1>`. It is considered best practice for a webpage to have only one h1 tag which represents the main title.🙏

2023-07-06 18:02 UTC, Shisui6 commented on index.html
> +                        </ul>
Kindly update this section to use a `<ul>` tag to wrap all the technology categories, as it is one of the project requirements🙏.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/37116322/219168802-9cd1f71f-48e1-45e6-85b9-38c7991e426d.png">

Also, ensure that each of the technology categories is also wrapped in `<li>` tags. 🫡

2023-07-06 18:02 UTC, Shisui6 commented on index.html
> +                    <button class="resume" type="button">Get my resume</button>
- Nice job styling your buttons when hovered. However the colours shown when the button is hovered over is not in line with the figma design. Please try to stick to the colors used in the figma design as much as possible. 
- Also, please apply styles to your buttons when they are pressed in accordance with the figma design. You can use the `:active` pseudo selector to achieve this

<img width="447" alt="image" src="https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/37116322/499ad6cd-319b-4a60-aba6-fdb97fa3bd2f">

2023-07-07 09:36 UTC, allenkays commented on index.html
> +            <section class="portfolio">
I've made the changes in css files to apply grid layout to this section

2023-07-07 09:37 UTC, allenkays commented on index.html
> +                    <h1 class="main-title">About me</h1>
I have changed this tag to <h2>. Thanks for the best practice reminder.

2023-07-07 09:46 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 10:18 UTC, merged