Setup desktop
allenkays/Portfolio-setup-and-mobile-first pull request #4
Opened 2023-07-15 21:23 UTC by allenkays

In this milestone I:
Added media queries to style for desktop.
Removed background images and linked them using css.

2023-07-15 21:50 UTC, usorfaitheloho requested changes
> Hi @allenkays  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * All linter checks passed ✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 21:50 UTC, usorfaitheloho commented on index.html
> +            </nav>
kindly ensure the logo is in the same vertical alignment with the headline section as it is in the design given so you'd have a good design 😄 . Also, I'd suggest you move the navigation items away from the border line a bit by adding some margin 👍 

Figma design :
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/47257a18-5cc3-4531-bba8-000fad3a5908)

Your design :
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/f786d344-a81c-4078-84d7-953166c330f8)

2023-07-15 21:50 UTC, usorfaitheloho commented on index.html
> +                    <h1 class="main-title"><span>Hey There. I'm Allan.</h1>span></h1>
Kindly add a closing tag to the `span` element on line 31 👍

2023-07-15 21:50 UTC, usorfaitheloho commented on index.html
> +                            <button class="s-button" type="button">See project</button>
Kindly add some margin-top to this section of your project, so it doesn't look clustered 😄 

Your design :
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/8b3c6bde-1ec5-49fa-bdd2-619911545337)

2023-07-15 21:50 UTC, usorfaitheloho commented on index.html
> +                                </div>
Kindly note that their seems to be an issue with this section as the technologies section is missing which is close to the contact-me section. Please check your design and fix it.

Your design :
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/9caa869e-8713-446b-a53b-9417cbc41518)

Figma design :

![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/58e6d193-65a7-4bf3-89fa-99794e2ec871)

2023-07-15 21:50 UTC, usorfaitheloho commented on index.html
>                      </form>
Also, for your contact section, kindly fix it so it is as close to the design as possible 👍 

Your design :
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/2dca49ae-6f8a-4b1b-b859-cf9711b7a168)

Figma design :

![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/20537712/14ad20e5-fa10-4279-ae88-4628c70cdc00)

2023-07-16 00:14 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @allenkays 

Great work on making the changes requested by a previous reviewer 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-16 00:14 UTC, KanzaTahreem commented on style.css
>  }
- [ ] Good job so far 👍 However, the logo is still not aligned with the headline section 😓 Kindly make sure to align the logo with the headline section as suggested [here](https://github.com/allenkays/Portfolio-setup-and-mobile-first/pull/4#discussion_r1264563670) for getting a design close to the figma template as much as possible ✨📌

![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/106119105/44d17107-8250-4369-a270-790317c118ff)

2023-07-16 00:14 UTC, KanzaTahreem commented on index.html
> +                    <h1 class="main-title"><span>Hey There. I'm Allan.</span></h1>span></h1>
- [ ] As [suggested](https://github.com/allenkays/Portfolio-setup-and-mobile-first/pull/4#discussion_r1264563862), kindly make sure to fix the `span` tag. Right now, I can see that `span` tag is rendering as 👇
 
![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/106119105/fbacc10a-ecd6-41d6-8477-e12d82f0d6f9)

2023-07-16 00:14 UTC, KanzaTahreem commented on style.css
- [ ] Good job for adding the technologies section as [suggested](https://github.com/allenkays/Portfolio-setup-and-mobile-first/pull/4#discussion_r1264574899) 🥇🥇 However, it is not looking close to the Figma template. Kindly make sure that after adding the section, it looks close to the Figma template as much as possible  ⛏🤓

![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/106119105/c97bd671-e496-4438-8bc2-a2e1a08c8897)

2023-07-16 00:14 UTC, KanzaTahreem commented on style.css
>  }
- [ ] Good job with the contact section so far 👍👍 Kindly make sure that it looks almost identical to the given Figma template as much as possible as [suggested](https://github.com/allenkays/Portfolio-setup-and-mobile-first/pull/4#discussion_r1264575018). Please fix this as well 😃
- [ ] Also, I noticed that **_First name and Last name_** labels are present in the contact form. Previously only the label for **_Full name_** was present for the name field. Kindly fix this also ⛏💪 In the last review, the reviewer didn't asked for adding the two input fields for name as it is given in the project requirements to use only one input field for it. However, kindly fix the design in terms of padding/margin/space and alignment for getting a design close to the Figma template as requested earlier 💪

![image](https://github.com/allenkays/Portfolio-setup-and-mobile-first/assets/106119105/32fdb6e3-6d2c-46ee-bb94-ef217b6b8300)

2023-07-19 14:51 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @allenkays 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please take note that since you're repeating the week with an unapproved PR, you'll have to submit a new PR for review as per the policies in Microverse

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-19 15:57 UTC, closed without merging